[http]
host = "127.0.0.1"
port = 8080
key = "ooo-secret-api-key"

[mailgun]
From = "me@domain.com"
Domain = "domain.com"
APIKey = "key-lalala"
PublicAPIKey = "pubkey-lalala"

[contacts]
alex = "alex@emails.com"
sam = "sam@emails.com"

[series]
"Gravity Falls" = ["alex", "sam"]
